### ISSUE TITLE
Start with system

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [ekreutz/CornerCal#1]
My app doesnt start with system, and there is no option for that, is it possible to add it? Thanks, in advance

**Comment by gordio** [comment]
Just go to Preference Panel -> Users & Groups -> Current User -> Login Items and drop Application to this list.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/141126/40027925-ee4d549e-57e4-11e8-81ef-d01c31079f86.png">

**Comment by diego-lipinski-de-castro** [comment]
It works, ty

**Comment by Scosh** [comment]
Hi. I know this issue is closed and that this is a standard macOS feature, but I was a bit confused about this and looking for the option to *start with system* in the `Settings` of CornerCal because I have a lot of status bar applications that auomate the process this way and I kinda forgot `Login Items` was even a thing on Mac.

Would it be possible to add this option into the `Settings` in a future update? I know it‘s a tiny thing; it‘s just an idea to maybe make the usability a little bit better if it isn‘t too much work.

Otherwise, if that isn’t possible or part of your plan, could one maybe just add a section to the `README` describing the process of adding CornerCal to the `Login Items` for newbies? Just like in your helpful comment. One could even just use the same text.
